In [1]:
import pandas as pd
import numpy as np
import pandasql as ps

In [2]:
targetSales = 5000000
dataCsv = pd.read_excel('cleanData.xlsx')

In [3]:
print(dataCsv.head())

   No.      Bulan        NAMACAB                 NAMALANG  \
0   80 2020-07-01  BANDARLAMPUNG            INDRA JAYA AP
1   81 2020-07-01  BANDARLAMPUNG                ENGGAL AP
2   82 2020-07-01  BANDARLAMPUNG     PELITA AP - KESHATAN
3   83 2020-07-01  BANDARLAMPUNG  TIJARA ANUGRAH FARMA PT
4  311 2020-07-01      TANGERANG                 NIDEA AP

                   NAMAPROD    HNA  BANYAK    THNA  PRSND  DHARGA TYPE OUTLET  \
0  PROPEPSA SUSPENSI 200 ML  85000       1   85000      0       0      APOTIK
1        D-VIT FLASH TABLET  75000       4  300000      0       0      APOTIK
2  PROPEPSA SUSPENSI 100 ML  57500       3  172500      0       0         NaN
3  PROPEPSA SUSPENSI 100 ML  57500      12  690000      0       0         PBF
4  PROPEPSA SUSPENSI 100 ML  57500       2  115000      0       0         NaN

      SUBRAYON                   AM
0  WAY HALIM 3         EKA CHAIRANI
1  RADEN INTAN         EKA CHAIRANI
2   AHMAD YANI    VACANT - WONOGIRI
3     ANTASARI  DAVIQ NOVADA AMD KL
4      CILEDUG  ELVIN OTTO MULIAWAN

In [4]:
dataFrame = pd.DataFrame(dataCsv)

In [6]:
allrows = ps.sqldf("select * from dataFrame")
allrows

,No.,Bulan,NAMACAB,NAMALANG,NAMAPROD,HNA,BANYAK,THNA,PRSND,DHARGA,TYPE OUTLET,SUBRAYON,AM
0,80,2020-07-01 00:00:00.000000,BANDARLAMPUNG,INDRA JAYA AP,PROPEPSA SUSPENSI 200 ML,85000,1,85000,0,0,APOTIK,WAY HALIM 3,EKA CHAIRANI
1,81,2020-07-01 00:00:00.000000,BANDARLAMPUNG,ENGGAL AP,D-VIT FLASH TABLET,75000,4,300000,0,0,APOTIK,RADEN INTAN,EKA CHAIRANI
2,82,2020-07-01 00:00:00.000000,BANDARLAMPUNG,PELITA AP - KESHATAN,PROPEPSA SUSPENSI 100 ML,57500,3,172500,0,0,None,AHMAD YANI,VACANT - WONOGIRI
3,83,2020-07-01 00:00:00.000000,BANDARLAMPUNG,TIJARA ANUGRAH FARMA PT,PROPEPSA SUSPENSI 100 ML,57500,12,690000,0,0,PBF,ANTASARI,DAVIQ NOVADA AMD KL
4,311,2020-07-01 00:00:00.000000,TANGERANG,NIDEA AP,PROPEPSA SUSPENSI 100 ML,57500,2,115000,0,0,None,CILEDUG,ELVIN OTTO MULIAWAN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
844,21372,2020-07-30 00:00:00.000000,BANDARLAMPUNG,APT POLYGON FARMA,NOFLAM 100 MG TABLET,237500,10,2375000,32,760000,APOTEK,JENDRAL SUDIRMAN,GALIH YOHANES
845,21373,2020-07-30 00:00:00.000000,BANDARLAMPUNG,APT POLYGON FARMA,PROPEPSA SUSPENSI 100 ML,57500,60,3450000,27,931500,APOTEK,JENDRAL SUDIRMAN,GALIH YOHANES
846,21374,2020-07-30 00:00:00.000000,BANDARLAMPUNG,APT POLYGON FARMA,FLAMIC 50 MG TABLET,162500,14,2275000,32,728000,APOTEK,JENDRAL SUDIRMAN,GALIH YOHANES
847,21375,2020-07-30 00:00:00.000000,BANDARLAMPUNG,APT POLYGON FARMA,PROPEPSA SUSPENSI 100 ML,57500,120,6900000,22,1518000,APOTEK,JENDRAL SUDIRMAN,GALIH YOHANES
848,21376,2020-07-30 00:00:00.000000,BANDARLAMPUNG,APT POLYGON FARMA,VERSYL TABLET,100000,10,1000000,32,320000,APOTEK,JENDRAL SUDIRMAN,GALIH YOHANES

In [8]:
username = input('input username : ')

input username : DANNIEL

In [9]:
print(username)

DANNIEL

In [108]:
dataFrameAmFilter = dataFrame.copy()
query = "select * from  dataFrameAmFilter where AM = '{}';".format(username)
dataFrameAmFilter = ps.sqldf(query)

In [109]:
query = "select sum(THNA) from  dataFrameAmFilter"
sumSales = np.array(ps.sqldf(query)).flatten().tolist()

90827250

In [41]:
dataProductFokus = dataFrameAmFilter.copy()
query = "select * from  dataFrameAmFilter where NAMAPROD like 'D-VIT%' "
query = query + "or NAMAPROD like 'CALNIC%'"
query = query + "or NAMAPROD like 'VOXIN%'"
query = query + "or NAMAPROD like 'CEFAROX%'"
query = query + "or NAMAPROD like 'GASTROLAN%'"
query = query + "or NAMAPROD like 'VOMISTOP%'"
query = query + "or NAMAPROD like 'ESTIN%'"
query = query + "or NAMAPROD like 'ZEMINDO%'"
query = query + "or NAMAPROD like 'BUSMIN%'"
query = query + "or NAMAPROD like 'HI-SQUA%'"
dataProductFokus = ps.sqldf(query)

In [42]:
dataProductFokus

,No.,Bulan,NAMACAB,NAMALANG,NAMAPROD,HNA,BANYAK,THNA,PRSND,DHARGA,TYPE OUTLET,SUBRAYON,AM
0,323,2020-07-01 00:00:00.000000,TANGERANG,EKA HOSPITAL,D-VIT FLASH TABLET,75000,4,300000,27,81000,None,SERPONG,DANNIEL
1,904,2020-07-02 00:00:00.000000,TANGERANG,BETHSAIDA HOSPITAL INTERNATIONAL PT,D-VIT FLASH TABLET,75000,27,2025000,22,445500,RS SWASTA,SERPONG,DANNIEL
2,905,2020-07-02 00:00:00.000000,TANGERANG,PERUMNAS DASANA AP,GASTROLAN 30 MG KAPSUL,280000,1,280000,0,0,None,KELAPA DUA,DANNIEL
3,906,2020-07-02 00:00:00.000000,TANGERANG,JURUMUDI AP,D-VIT SYRUP,30000,4,120000,32,38400,None,SUKARASA,DANNIEL
4,1345,2020-07-03 00:00:00.000000,TANGERANG,PHARMAPLUS (ALAM SUTERA) AP,CALNIC 100 ML SUSPENSI,55000,6,330000,0,0,APOTIK,SUDIMARA 2,DANNIEL
...,...,...,...,...,...,...,...,...,...,...,...,...,...
84,20489,2020-07-30 00:00:00.000000,TANGERANG,DUTA SEHAT AP,ZEMINDO SYRUP,37500,12,450000,27,121500,APOTIK,SEPATAN,DANNIEL
85,20490,2020-07-30 00:00:00.000000,TANGERANG,BETHSAIDA HOSPITAL INTERNATIONAL PT,D-VIT FLASH TABLET,75000,31,2325000,22,511500,RS SWASTA,SERPONG,DANNIEL
86,20499,2020-07-30 00:00:00.000000,TANGERANG,EKA HOSPITAL,D-VIT FLASH TABLET,75000,10,750000,27,202500,None,SERPONG,DANNIEL
87,20850,2020-07-30 00:00:00.000000,TANGERANG,LILY FARMA AP - TANGERANG,D-VIT FLASH TABLET,75000,2,150000,0,0,None,GADING SERPONG,DANNIEL
88,20853,2020-07-30 00:00:00.000000,TANGERANG,LILY MEDIKA SEHAT AP,CALNIC 30 PLUS KAPLET,138000,1,138000,27,37260,None,KELAPA DUA,DANNIEL

In [78]:
# dataFrameAmFilterApotek = dataFrameAmFilter.loc[(dataFrameAmFilter['TYPE OUTLET'] == 'APOTIK') |(dataFrameAmFilter['TYPE OUTLET'] == 'APOTEK') ]
query = "select DISTINCT NAMALANG from  dataProductFokus where \"TYPE OUTLET\" = 'APOTIK' or 'TYPE OUTLET' = 'APOTEK'; "
dataApotek = np.array(ps.sqldf(query)).flatten().tolist()

In [79]:
print(dataApotek)
dispenList = []
while(1):
    userinput = str(input('masukan nama Apotik Langganan yang dispen (biarkan kosong untuk selesai)'))
    if userinput == '' :
        break;
    if userinput in dataApotek:
        dispenList.append(userinput)
        dataApotek.remove(userinput)
    else :
        print('Inputan tidak Cocok untuk data Apotek / sudah diinput sebelumnya')

['PHARMAPLUS (ALAM SUTERA) AP', 'PERUMNAS AP', 'MOM & CHILD CARE CLINIC AP', 'TIRTA SARI AP', 'CK FARMA AP', 'HARAPAN JAYA AP', 'BINTANG FORTUNA AP', 'MILLENNIUM PHARMA AP', 'DUTA SEHAT AP']
masukan nama Apotik Langganan yang dispen (biarkan kosong untuk selesai)PHARMAPLUS (ALAM SUTERA) AP
masukan nama Apotik Langganan yang dispen (biarkan kosong untuk selesai)PHARMAPLUS (ALAM SUTERA) AP
Inputan tidak Cocok untuk data Apotek / sudah diinput sebelumnya
masukan nama Apotik Langganan yang dispen (biarkan kosong untuk selesai)PERUMNAS AP
masukan nama Apotik Langganan yang dispen (biarkan kosong untuk selesai)

In [80]:
dispenList

['PHARMAPLUS (ALAM SUTERA) AP', 'PERUMNAS AP']

In [84]:
listApotekDispen = pd.DataFrame(dispenList, columns = ['dispen'])

In [85]:
listApotekDispen

                        dispen
0  PHARMAPLUS (ALAM SUTERA) AP
1                  PERUMNAS AP

In [86]:
query = "select * from  dataProductFokus where \"NAMALANG\" not in (select dispen from listApotekDispen)"
filterDataProductFokus = ps.sqldf(query)

In [87]:
filterDataProductFokus

,No.,Bulan,NAMACAB,NAMALANG,NAMAPROD,HNA,BANYAK,THNA,PRSND,DHARGA,TYPE OUTLET,SUBRAYON,AM
0,323,2020-07-01 00:00:00.000000,TANGERANG,EKA HOSPITAL,D-VIT FLASH TABLET,75000,4,300000,27,81000,None,SERPONG,DANNIEL
1,904,2020-07-02 00:00:00.000000,TANGERANG,BETHSAIDA HOSPITAL INTERNATIONAL PT,D-VIT FLASH TABLET,75000,27,2025000,22,445500,RS SWASTA,SERPONG,DANNIEL
2,905,2020-07-02 00:00:00.000000,TANGERANG,PERUMNAS DASANA AP,GASTROLAN 30 MG KAPSUL,280000,1,280000,0,0,None,KELAPA DUA,DANNIEL
3,906,2020-07-02 00:00:00.000000,TANGERANG,JURUMUDI AP,D-VIT SYRUP,30000,4,120000,32,38400,None,SUKARASA,DANNIEL
4,2730,2020-07-06 00:00:00.000000,TANGERANG,ARCHA MEDICA AP,CALNIC 100 ML SUSPENSI,55000,3,165000,0,0,None,SERPONG,DANNIEL
...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,20489,2020-07-30 00:00:00.000000,TANGERANG,DUTA SEHAT AP,ZEMINDO SYRUP,37500,12,450000,27,121500,APOTIK,SEPATAN,DANNIEL
71,20490,2020-07-30 00:00:00.000000,TANGERANG,BETHSAIDA HOSPITAL INTERNATIONAL PT,D-VIT FLASH TABLET,75000,31,2325000,22,511500,RS SWASTA,SERPONG,DANNIEL
72,20499,2020-07-30 00:00:00.000000,TANGERANG,EKA HOSPITAL,D-VIT FLASH TABLET,75000,10,750000,27,202500,None,SERPONG,DANNIEL
73,20850,2020-07-30 00:00:00.000000,TANGERANG,LILY FARMA AP - TANGERANG,D-VIT FLASH TABLET,75000,2,150000,0,0,None,GADING SERPONG,DANNIEL
74,20853,2020-07-30 00:00:00.000000,TANGERANG,LILY MEDIKA SEHAT AP,CALNIC 30 PLUS KAPLET,138000,1,138000,27,37260,None,KELAPA DUA,DANNIEL

In [113]:

if sumSales[0] >= targetSales : 
    query = "select (sum(THNA) - 5000000) * 7.5/100 as \"Incentive Product Fokus\" from filterDataProductFokus "
    IPF = np.array(ps.sqldf(query)).flatten().tolist()
    TotalIncentive = IPF[0]
else :
    TotalIncentive = 0

In [114]:
TotalIncentive

0

[3232875.0]